sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 327020

#  alioss:
#    access-key-secret:
#    bucket-name:
#    access-key-id:
  redis:
    host: localhost
    port: 6379
    database: 0

